### ISSUE TITLE
Error: 'MapLiteral' isn't a type.

### ISSUE THREAD

**Issue by michaelu123** [MikeMitterer/dart-l10n-gettext#6]
The command flutter pub global activate l10n terminates with
...
Precompiling executables...
Failed to precompile l10n:mkl10n:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/l10n-2.0.19/lib/extractor/L10NMessageExtraction.dart:159:56: Error: 'MapLiteral' isn't a type.
        if(arguments.length == 2 && arguments.last is! MapLiteral) {
                                                       ^^^^^^^^^^

**Comment by michaelu123** [comment]
Sorry wrong package,

**Comment by michaelu123** [comment]
Apparently a duplicate of https://github.com/flutter/gallery/issues/324

**Comment by reidlai** [comment]
how can we solve this problem?

**Comment by gabrielGavriluta** [comment]
pub global activate --source git https://github.com/Delagen/dart-l10n-gettext
